<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>rawrr</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0" />
    <PackageReference Include="ThermoFisher.CommonCore.BackgroundSubtraction" Version="8.0.6" />
    <PackageReference Include="ThermoFisher.CommonCore.Data" Version="8.0.6" />
    <PackageReference Include="ThermoFisher.CommonCore.MassPrecisionEstimator" Version="8.0.6" />
    <PackageReference Include="ThermoFisher.CommonCore.RawFileReader" Version="8.0.6" />
  </ItemGroup>
</Project>

