name: CD RawrrAssembly
on:
  workflow_dispatch:
  release:
    types: [published]
env:
  DOTNET_DOCKER: mcr.microsoft.com/dotnet/sdk:8.0
jobs:
  build:
    name: Build Executables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pull .NET Docker image
        run: docker pull $DOTNET_DOCKER
      - name: Build executables
        run: |
          cd inst/rawrrassembly
          docker run --rm -v $PWD:/app -w /app $DOTNET_DOCKER /app/build.sh /app /app/out
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rawrr-executables
          path: inst/rawrrassembly/out/rawrr-*
          retention-days: 1
  verify-linux:
    name: Verify on Linux
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: rawrr-executables
          path: ./executables
      - name: List executables
        run: ls -lh ./executables
      - name: Make executable
        run: chmod +x ./executables/rawrr-linux-x64
      - name: Execute on test file
        run: ./executables/rawrr-linux-x64 ./inst/extdata/sample.raw index
  verify-windows:
    name: Verify on Windows
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: rawrr-executables
          path: .\executables
      - name: List executables
        run: dir .\executables
      - name: Execute on test file
        run: .\executables\rawrr-win-x64.exe .\inst\extdata\sample.raw index
  verify-macos:
    name: Verify on MacOS
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: rawrr-executables
          path: ./executables
      - name: List executables
        run: ls -lh ./executables
      - name: Make executable
        run: chmod +x ./executables/rawrr-osx-x64
      - name: Execute on test file
        run: ./executables/rawrr-osx-x64 ./inst/extdata/sample.raw index
  upload-release-artifacts:
    name: Upload Release Artifacts
    runs-on: ubuntu-latest
    needs:
      - verify-linux
      - verify-windows
      - verify-macos
    if: github.event_name == 'release'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: rawrr-executables
          path: ./executables
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            executables/rawrr-linux-x64
            executables/rawrr-win-x64.exe
            executables/rawrr-osx-x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
